[package]
name = "kasky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting = "0.11.1"
rustyline = "12.0.0"
crossterm = "0.27.0"
